CREATE TABLE IF NOT EXISTS links (
    id SERIAL PRIMARY KEY,
    original_url VARCHAR(255) NOT NULL,
    short_name VARCHAR(255) NOT NULL UNIQUE,
    short_url VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ DEFAULT NOW()
);